In [48]:
import torch 

In [49]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [54]:
y = x + 2
print(y)
y.grad_fn
z = y * y * 3
out = z.mean()

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [57]:
out.backward()

In [58]:
x.grad


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])