In [4]:
import tensorflow as tf 
from tensorflow.keras import layers

### embedding层

In [7]:
x = tf.range(10) # 生成10个单词的数字编码
x = tf.random.shuffle(x) # 打散
# 创建共10个单词，每个单词用长度为4的词向量表示的层
net = layers.Embedding(10, 4)
out = net(x) # 获取词向量

### simpleRNNCell

In [14]:
cell = layers.SimpleRNNCell(3) # 
cell.build(input_shape=(None, 4))
cell.trainable_variables

[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.4753338 ,  0.77290404, -0.5207639 ],
        [-0.22367418,  0.40107775,  0.3295288 ],
        [ 0.5261164 ,  0.90216506,  0.22214079],
        [ 0.7200396 ,  0.5737921 ,  0.7176019 ]], dtype=float32)>,
 <tf.Variable 'recurrent_kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.66041446,  0.17118202, -0.73112893],
        [ 0.7415409 ,  0.00458086,  0.67089206],
        [-0.11819384,  0.98522884,  0.12391309]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [15]:
# 初始化状态向量，用列表包裹，统一格式
h0 = [tf.zeros([4, 64])]
x = tf.random.normal([4, 80, 100])
xt = x[:, 0, :] # 所有句子的第1个单词
cell = layers.SimpleRNNCell(64)
out, h1 = cell(xt, h0)
print(out.shape, h1[0].shape)

(4, 64) (4, 64)


In [16]:
print(cell.trainable_variables)

[<tf.Variable 'simple_rnn_cell_2/kernel:0' shape=(100, 64) dtype=float32, numpy=
 array([[ 0.03535517,  0.14948021,  0.07307623, ..., -0.02776171,
          0.08764721,  0.05298425],
        [-0.16031827, -0.15616907,  0.05125964, ...,  0.15466468,
         -0.0346694 , -0.17176248],
        [-0.01047529, -0.17942882,  0.01539038, ...,  0.09280826,
          0.08615367, -0.1688209 ],
        ...,
        [ 0.03038654,  0.18205939, -0.05751233, ..., -0.0188766 ,
         -0.1656006 ,  0.07365032],
        [ 0.15264817, -0.01607955,  0.13656737, ...,  0.16937207,
         -0.08111645,  0.10855119],
        [-0.11303589,  0.19025747, -0.03144768, ...,  0.14847593,
         -0.00880066,  0.02582245]], dtype=float32)>,
 <tf.Variable 'simple_rnn_cell_2/recurrent_kernel:0' shape=(64, 64) dtype=float32, numpy=
 array([[ 0.12915576, -0.30560005,  0.17059438, ...,  0.04052937,
          0.11068136,  0.08433112],
        [ 0.12508404, -0.10253453,  0.05845955, ..., -0.03166014,
         -0.213281